---
- name: Add java repo key
  apt_key: id=EEA14886 keyserver=keyserver.ubuntu.com

- name: Add java repo
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main' state=present update_cache=yes

- name: License agree
  debconf: name=oracle-java8-installer question="shared/accepted-oracle-license-v1-1" value='true' vtype='select'

- name: Install java
  apt: name=oracle-java8-installer
